### ISSUE TITLE
train.toml出错

### ISSUE THREAD

**Issue by Cagemoney** [RookieJunChen/FullSubNet-plus#25]
你好呀，我在复现你的工作的时候发现，train.toml出错了，我发现是因为snr_range = [-5,20]和metrics = ["WB_PESQ", "NB_PESQ", "STOI", "SI_SDR"]这里有问题，把这两行注释掉就没问题。我在网上没找到解决方法，请问您遇到过这样的问题吗？期待您的回复

**Comment by RookieJunChen** [comment]
方便提供一下你的报错信息吗？

**Comment by Cagemoney** [comment]
代码还没跑起来，是在查看代码的时候发现了这个情况。我粘贴了一张图片，不知道你能不能看到。
![Uploading 16843791894827.png…]()

**Comment by RookieJunChen** [comment]
我看不到图片，是IDE报错吗？IDE报错代码能跑起来的话你就别管IDE了？

**Comment by Cagemoney** [comment]
![16843791894827](https://github.com/RookieJunChen/FullSubNet-plus/assets/61931515/7131a157-7f49-4f4e-ba98-e0b0750b2fef)

**Comment by RookieJunChen** [comment]
IDE提示报错不影响的，代码能跑起来就行

**Comment by Cagemoney** [comment]
噢噢好的，谢谢你
