### ISSUE TITLE
torch.istft requires a complex-valued input tensor matching the output from stft with return_complex=True

### ISSUE THREAD

**Issue by HuuHuy227** [RookieJunChen/FullSubNet-plus#26]
I know this issue because from torch 2.0+ Real datatype inputs are no longer supported. So any solution for this problem?

**Comment by HuuHuy227** [comment]
Fixing by downgrade to torch 1.12

**Comment by lpfahhh** [comment]
Hello, I also encountered this problem, but the graphics card has a computing power of 89ms. It seems that it is only supported by torch2.x or above. After downgrading, an error will be reported. What should I do?

**Comment by lpfahhh** [comment]
add code ‘ enhanced = self.torch_istft(enhanced_complex, length=noisy.size(-1))’ after trainer.py 410
